<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Back Office</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="assets/css/cocktails.css">
</head>

<body class="container">
        <?php include 'inc/nav.phtml'; ?>
        <h1>Back Office</h1>
    
    <main class="row mt-5">
        <div class="col-12">
            <?= $messageSession; ?>
            <table class="table table-bordered text-light text-center">
                <thead class="bg-light text-dark">
                    <tr>
                        <th>#</th>
                        <th>NOM</th>
                        <th>PHOTO DU COCKTAIL</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <?php foreach ($listeCocktails as $table) { ?>
                    <tr class="tableau">
                        <th><?= $table['id'] ?></th>
                        <th><?= $table['nom'] ?></th>
                        <th><img src="assets/images/cocktails/<?= $table['urlPhoto'] ?>" width="100" alt=""></th>
                        <th><a href="editionCocktail.php?action=modifier&id=<?= $table['id'] ?>" class="btn btn-warning"><i class="far fa-edit"></i></a></th>
                        <th><a href="?action=supprimer&id=<?= $table['id'] ?>" onclick="return(confirm('Êtes-vous sur ?'))" class="btn btn-danger"><i class="far fa-trash-alt"></i></a></th>
                    </tr>
                <?php } ?>

                <tbody>

                </tbody>
            </table>
        </div>

    </main>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>