<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fiche cocktail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="assets/css/cocktails.css">
</head>

<body class="container">

    <?php include 'inc/nav.phtml'; ?>
    <h1> <?= $infosCocktail['nom'] ?> <i class="fas fa-cocktail"></i></h1>


    <main class="row mt-5">
        <div class="col-sm-6">
            <img src="assets/images/cocktails/<?= $infosCocktail['urlPhoto'] ?>" alt="Image du cocktail : <?= $infosCocktail['nom'] ?>" class="w-100 img-thumbnail">
        </div>
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item bg-dark text-white"><?= $infosCocktail['nom'] ?></li>
                <li class="list-group-item">Famille : <a href="index.php?famille=<?= $infosCocktail['nomFamille'] ?>"><?= $infosCocktail['nomFamille'] ?></a></li>
                <li class="list-group-item">Année de conception : <?= $infosCocktail['anneeConception'] ?></li>
                <li class="list-group-item">Prix moyen : <?= $infosCocktail['prixMoyen'] ?> <b>€</b></li>
            </ul>
            <p class="text-white text-justify mt-4 bg-dark p-3 border"><u>Ingrédients</u>:<br>
            <?php 
                    foreach($listeIngredients AS $ingredient) { 
                        echo '- ' . $ingredient['nomIngredient'] . '<br>';
                    }
            ?>
            </p>
            <p class="text-white text-justify mt-4 bg-dark p-3 border"><u>Description</u>: <?= $infosCocktail['description'] ?></p>

        </div>

    </main>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>