<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un cocktail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="assets/css/cocktails.css">
</head>

<body class="container">
        <?php include 'inc/nav.phtml'; ?>
        <h1>Modifier un cocktail</h1>

    <main class="row">
        <div class="col-sm-8 mx-auto">
            <form method="post" class="border p-3">
            <?= $msg; //variable destinée à afficher message utilisateur?>
            <!-- on cache id par sécurité, pour pas que l'administrateur merde avec -->
                <input type="hidden" name="id" value="<?= $infosCocktail['id'] ?>">

                <div class="form-group">
                    <label for="nom">Nom</label>
                    <input type="text" id="nom" name="nom" class="form-control" value="<?= $infosCocktail['nom'] ?>">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea type="text" id="description" name="description" class="form-control"><?= $infosCocktail['description'] ?></textarea>
                </div>
                <div class="form-group">
                    <label for="prixMoyen">Prix Moyen</label>
                    <input type="text" id="prixMoyen" name="prixMoyen" class="form-control" value="<?= $infosCocktail['prixMoyen'] ?>">
                </div>
                <div class="form-group">
                    <label for="anneeConception">Année de conception</label>
                    <input type="text" id="anneeConception" name="anneeConception" class="form-control" value="<?= $infosCocktail['anneeConception'] ?>">
                </div>
                <div class="form-group">
                    <label for="famille">Famille</label>
                    <select id="famille" name="famille" class="form-control">
                        <?php foreach ($listeFamille as $famille) { ?>
                            <?php if ($famille['id'] == $infosCocktail['idFamille']) { ?>
                                <option value="<?= $famille['id'] ?>" selected><?= $famille['nomFamille'] ?></option>
                            <?php } else { ?>
                                <option value="<?= $famille['id'] ?>"><?= $famille['nomFamille'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
                <button type="text" name="modifier" id="modifier" class="w-100 btn btn-outline-light text-light bg-dark" value="Modifier">Modifier</button>

            </form>
        </div>
    </main>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>